controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller

    type: attribute

#app_base:
#        path: /
#        controller: App\Controller\IndexController::index


